
# Terraform Infra
# Node: aws_vm1
# Time: 1774808671

resource "aws_instance" "aws_vm1" {
  // Assuming the instance ID is correct
  id = "aws_vm1"

  // Apply the safe and secure patch
  lifecycle {
    ignore_changes = [
      // Ignore any changes to the instance's patch ammendments
      patch_amendment {
        id,
        description,
        description_format,
        description_format_version,
        description_version,
        description_version_format,
        description_version_format_version,
        description_version_format_version_description,
        description_version_format_version_description_format,
        description_version_format_version_description_format_version,
        description_version_format_version_description_format_version_description,
        description_version_format_version_description_format_version_description_format,
        description_version_format_version_description_format_version_description_format_version,
        description_version_format_version_description_format_version_description_format_version_description,
        description_version_format_version_description_format_version_description_format_version_description_format,
        description_version_format_version_description_format_version_description_format_version_description_format_version,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description,
        description_version_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version_description_format_version
