package gitops

import graphpkg "github.com/diya-suryawanshi/cloud/graph-engine/graph"

// This struct represents a decision taken for a node
type Decision struct {
	NodeID      string  // ID of the node on which action is applied
	Action      string  // original action suggested
	FinalAction string  // final action after validation
	Score       float64 // score used for decision making
	Reason      string  // reason behind the decision
}

// This struct stores differences between old and new graph
type Diff struct {
	NodeID    string                 // node on which change is detected
	OldState  map[string]interface{} // previous state of node
	NewState  map[string]interface{} // updated state of node
	ChangeSet []string               // list of detected changes
}

// This struct stores infrastructure code generated by GenAI
type InfraCode struct {
	Content string // generated code (e.g., terraform)
	Format  string // format of code
}

// This struct stores Pull Request response details
type PRResponse struct {
	URL      string // PR link
	Status   string // status of PR (created/failed)
	PRNumber int    // PR number from GitHub
	Branch   string // branch name used for PR
}

// Graph type is reused from graph-engine package
type Graph = graphpkg.Graph
